name: credpal_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  google_fonts: ^6.2.1
  flutter_gen: ^5.10.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.9

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    json: true

  assets:
    enabled: true
    outputs:
      class_name: CredpalAssets

flutter:
  uses-material-design: true
